server:
  port: 9000

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: '#adminadmin1'
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
